# Site settings
title: My Personal Webiste
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
# User settings
username: Hudhayfa Jamalkhan
user_title: Web Developer
email: hudhayfajamalkhan@gmail.com
github_username:  savaris
linkedin_username: hudhayfajamalkhan
user_description: Whilst undertaking the WDI(Web Development Immersive) course at General Assembly, I developed my skills in the following as evidenced by the projects that I produced.

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
